# Generated by Django 3.2.3 on 2021-05-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_board_contents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시글', 'verbose_name_plural': '게시글'},
        ),
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
