# Generated by Django 3.2.3 on 2021-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210517_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password',
            field=models.CharField(default=1111, max_length=64, verbose_name='비밀번호'),
            preserve_default=False,
        ),
    ]
