# Generated by Django 3.2.3 on 2021-05-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20210516_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcuser',
            table='fcuser',
        ),
    ]
