# Generated by Django 3.2.3 on 2021-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(null=True, upload_to='', verbose_name='파일'),
        ),
    ]
