# Generated by Django 3.2.3 on 2021-06-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='hit',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
