# Generated by Django 3.2.3 on 2021-06-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_active'),
        ('board', '0002_alter_board_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_boards', to='user.User'),
        ),
    ]
