# Generated by Django 3.2.3 on 2021-06-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='password',
        ),
    ]
