# Generated by Django 3.2.3 on 2021-06-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_board_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='groupno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='orderno',
            field=models.IntegerField(default=0),
        ),
    ]
