# Generated by Django 3.2.3 on 2021-06-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210622_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d', verbose_name='파일'),
        ),
    ]
