# Generated by Django 3.2.3 on 2021-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_board_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d')),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='file',
        ),
        migrations.RemoveField(
            model_name='board',
            name='file_path',
        ),
        migrations.AddField(
            model_name='board',
            name='files',
            field=models.ManyToManyField(to='board.BoardFile'),
        ),
    ]
